reference:
  "/Users/liting/01_data/20230407/references/GRCh37_decoy/references_hs37d5_hs37d5.fa"
backbones:
  "/Users/liting/01_data/20230407/backbones/*"
input_dir:
  "/Users/liting/01_data/20230407"
out_dir:
  "/Users/liting/01_data/20230407/20230419-output1"
sample_tsv:
  "/Users/liting/01_data/20230407/samplesheet.csv"
