reference:
  "/hpc/compgen/projects/gw_cfdna/gw_cyclomics/analysis/lchen/smk-gwcyclomicsseq/data/reference/hs37d5.fasta"
backbones:
  "/hpc/compgen/projects/gw_cfdna/gw_cyclomics/analysis/lchen/smk-gwcyclomicsseq/data/backbones/*"
input_dir:
  "/hpc/compgen/projects/gw_cfdna/gw_cyclomics/analysis/lchen/smk-gwcyclomicsseq/data"
out_dir:
  "/hpc/compgen/projects/gw_cfdna/gw_cyclomics/analysis/lchen/smk-gwcyclomicsseq-working/20230418-test-output"
sample_tsv:
  "/hpc/compgen/projects/gw_cfdna/gw_cyclomics/analysis/lchen/smk-gwcyclomicsseq/data/samplesheet.csv"
